### ISSUE TITLE
DHL API 

### ISSUE THREAD

**Issue by Flieger37** [glance-/dhl#10]
DHL provides two credential keys: the "API secret" and the "API key". 

Is the API key sufficient, or should both keys (and if so: how) be entered in the config.yaml?

I recognized that the question also came up in an already closed request (#5), but it wasn't answered and the guy ("IIIdefconIII")who asked didn't tell how he solved it.

Regards
Martin

**Comment by glance-** [comment]
It's neither "API secret" or "API key" you need. You need the "DHL-API-Key".

See the current documentation at https://developer.dhl.com/api-reference/shipment-tracking#get-started-section/user-guide--authentication.

**Comment by Flieger37** [comment]
Hi, thanks for your answer, but that does not solve the/my problem (sorry!):

First of all the correct API (of many DHL APIs) has to be chosen: your link points to the DHL API "Shipment Tracking - Unified". And that's exactly the API that I have requested from DHL and that's active.

As stated in the above link. "Every call to the API requires **a subscription key**. This key needs to be passed through **a request header (DHL-API-Key)**." - so "DHL-API-KEY" is the request header, but not the subscription key itself.

Than I think there is a mistake in the documentation of DHL. They write "Click the Show link below the asterisks that is hiding the **Consumer Key**.  The Consumer Key appears." They have this picture to illustrate:

<img width="531" alt="DHL-documentation" src="https://github.com/user-attachments/assets/2853e16d-a470-40dd-81d2-95bbea62ff54">

Screenshot of the DHL documentation (your above link).

But in fact the reality is like this:

<img width="946" alt="DHL-real world" src="https://github.com/user-attachments/assets/0881996c-ea51-4ced-8e2c-9da7de918bc5">

Screenshot of my API DHL dashboard - it shows an "**API key**" instead of the "Consumer key"..

So it seams that the "subscription key", which is documented as "Consumer Key" is in fact the "API key".

And that's the key, that I put im my CONFIG.YAML (without the **"secret"**) - but I don't get a result other than "unknown" for the packages after registering a valid tracking code.

My question is: am I wrong? Can you verify the above in your DHL Account-Dashboard? Is it working for you? Or did DHL change the API-call as they moved from "consumer key" to "API key"?

regards
Martin

**Comment by glance-** [comment]
I have no clue about what DHL might have done, so you need to take that up with them.

It wasn't this convoluted 3 years ago when I wrote this, but some reverse engineering shows that the "API Key" that shows up on my developer accounts registered app is in fact the DHL-API-Key I use.

I don't have any dhl packets currently so I can't test this but I think it worked back in April last time I used this.

Some other apis like these have some "example"-id's in their documentation that can be used to test your api usage with, but it I can't find any such in the dhl documentation.

**Comment by Flieger37** [comment]
Thanks for your answer, Anton.

OK, then we are talking about the same key and it should work, but didn't. I tested it yesterday evening with a valid/actual tracking number and double checked config.yaml and the key itself.

**BUT** suddenly this morning without having done anything: it's running. I found out, that it takes some time at DHL to activate the key, even if the dashboard says it's active.

Conclusion - if you like to update your Github documentation:

- You need the **DHL API "Shipment Tracking - Unified"**.
- You have to use the **API-Key** that's shown on the DHL API Dashboard
- You do **NOT** need the API Secret
-  You have to **be patient**, because DHL takes some time to activate the API key even if the dashboard says it is active (maybe they run a batch activation job over night)

Regards and many thanks!
Martin
