### ISSUE TITLE
Entities wont update

### ISSUE THREAD

**Issue by Lux315** [glance-/dhl#3]
Thanks for your work here, it works mostly very good.

The problem is refreshing the entities to get their new states. Is there a way to control the polling or just trigger a refresh without doing unregister and register again?

**Comment by glance-** [comment]
It's run on a default scan interval of 1800 seconds, https://github.com/glance-/dhl/blob/master/sensor.py#L38 , but that can be overridden in the configuration:
```yaml
sensor:
  - platform: dhl
    scan_interval: 90
```

I think it should be possible to trigger a manual refresh of the state with ```homeassistant.update_entity``` to, but it's way to long ago I wrote this to remember.

**Comment by Lux315** [comment]
Thank you very much for your fast reply!

**Comment by Lux315** [comment]
Hi @glance-,

this doesnt seem to fix the problem. The problem is, that the state is not getting updated in homeassistant when the state of the DHL Package changes in the DHL app.

It only gets updated if i unregister it and register it again. Changing the polling doesnt change anything.

Maybe if you got time, id be very happy if you take a look, if theres a solution for that.

**Comment by glance-** [comment]
The polling runs on the same homeassistant.util.Throttle scheme as all the other freight integrations I've wrote, and, I haven't gotten any dhl packages in a while, but I know for a fact that the PostNord sensor polling works. I got a couple of packets from them last week and those did update just as they should.

You can turn on debug logging for the component, and then you'll get a dump of the json data from the api on each poll cycle. Check that it actually happens. If not something's broken in your home-assistant setup causing the Throttle not to happen, and if it happens you can check that the updated data is actually there. If the data is actually there, something else might be detonating, which you will probably see in the debug logs then.

If you find something erroring out in the logs, post them here and I'll take a look.

**Comment by glance-** [comment]
I noted by accident that I actually had a dhl packet on my way, and did some digging.

The polling happened on the selected scan_interval as I thought, but I noted that the forcing of a update didn't work by calling `homeassistant.update_entity` so I fixed that.

Also I switched to using the statusCode for state on the packages, instead of the more descriptive status filed which was just to long. I'm not shure this was apart of the api when I wrote this code, but hey, looks prettier now.

So, yes, the scan_interval actually works for me.

**Comment by Lux315** [comment]
Hey,

thank you for your work and time, i updated instantly after it came and works perfectly now for me. 

Thx for your fast reply! I really like the integration. Unfortunatly theres nothing like this for Hermes, GLS and some other german shipment methods.
