### ISSUE TITLE
Request some support help get it working

### ISSUE THREAD

**Issue by IIIdefconIII** [glance-/dhl#5]
![image](https://github.com/glance-/dhl/assets/9917659/89e2e9e5-f0eb-4752-9278-9595383f2a18)
because myne isnt do much atm tbh

C ould you also tell me where to find the exact
{"package_id": "123456789"}

![image](https://github.com/glance-/dhl/assets/9917659/fbfcb35b-46ea-4f93-93d8-ccbcea449d64)

**Comment by glance-** [comment]
Parse error. I'm having quite a hard time trying to understand what your trying to say.

You need the bits that goes into the `DHL-API-Key` header. It's more than 5 years I registered for the key I'm using and I have no memory of that. Also they have probably re-designed the pages since then.

From [https://developer.dhl.com/api-reference/shipment-tracking#get-started-section/ one can read:
](https://developer.dhl.com/api-reference/shipment-tracking#get-started-section/user-guide--authentication) one can read that it's the "Consumer Key" you're supposed to use.

**Comment by IIIdefconIII** [comment]
> Parse error. I'm having quite a hard time trying to understand what your trying to say.
> 
> You need the bits that goes into the `DHL-API-Key` header. It's more than 5 years I registered for the key I'm using and I have no memory of that. Also they have probably re-designed the pages since then.
> 
> From [https://developer.dhl.com/api-reference/shipment-tracking#get-started-section/ one can read: ](https://developer.dhl.com/api-reference/shipment-tracking#get-started-section/user-guide--authentication) one can read that it's the "Consumer Key" you're supposed to use.

Thanks for ur asnwer,
Because of your anwer i say on the link you have send i used the wrong api tracking an deleted it and created a new APP in DHL dev pages.
![image](https://github.com/glance-/dhl/assets/9917659/89c419e3-b4e4-4898-86c1-672ec90c1a82)
Hope its going to work soon when its approved.
Iguess they renamed the Consumer key to api key
and the api secret was .. consumer secret but i guess i dont need that, just the API (consumer) Key
Thanks alot so far!

**Comment by IIIdefconIII** [comment]
Ok rutte ill try again later this week


Met vriendelijke groet,

________________________ _______________________
Thomas van Dalen

E: ***@***.******@***.***>

T: +316 30 929 009

________________________________

**Comment by IIIdefconIII** [comment]
cant get it to work and not sure what im doing wonrg to be honest, can anyone help me out?

**Comment by wuppiwuppi** [comment]
Have the same issues. Needs an improved manual to "which of the bits are needed where"

**Comment by Flieger37** [comment]
> get it working [on Mar 18]

How did you solve it?

**Comment by glance-** [comment]
A quick search in the docs I came across https://developer.dhl.com/api-reference/shipment-tracking#get-started-section/user-guide--authentication

That says how you get your DHL-API-Key, which is what the api needs.
